branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: celery-stalk
  branch: null
  default_ec2_keyname: chainstay
  default_platform: python-2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: chainstay-terraform
  repository: null
  sc: git
  workspace_type: Application
