version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Creating Dockerrun.aws.json files for web and worker...
      - apt-get update
      - apt-get install -y gettext-base
      - mkdir web worker
      - export VERSION=latest
      - envsubst < deploy/Dockerrun.WEB.aws.json > web/Dockerrun.aws.json
      - envsubst < deploy/Dockerrun.WORKER.aws.json > worker/Dockerrun.aws.json
artifacts:
  secondary-artifacts:
    dockerrunweb:
      base-directory: ./web
      files:
        - Dockerrun.aws.json
    dockerrunworker:
      base-directory: ./worker
      files:
        - Dockerrun.aws.json
